
esphome:
  name: WeatherBom
  friendly_name: BOM Weather
  
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: github://andrewbackway/esphome-weather_bom@main
    refresh: 1s

logger:
  level: DEBUG

api:

wifi:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

captive_portal:

web_server:
  version: 3

time:
  - platform: sntp
    id: sntp_time
    timezone: Melbourne/Australia
    servers:
      - 0.au.pool.ntp.org
      - 1.au.pool.ntp.org
      - 2.au.pool.ntp.org

sensor:
  - platform: template
    id: gps_lat
    name: "GPS Latitude"
    lambda: |-
      return -37.8136;
  - platform: template
    id: gps_lon
    name: "GPS Longitude"
    lambda: |-
      return 144.9631;

weather_bom:
  latitude_sensor: gps_lat
  longitude_sensor: gps_lon
  update_interval: 300s

  temperature:
    name: "Weather Temperature"
  humidity:
    name: "Weather Humidity"
  wind_speed_kmh:
    name: "Weather Wind Speed (km/h)"
  rain_since_9am:
    name: "Weather Rain Since 9AM"

  today_min:
    name: "Weather Today Min Temp"
  today_max:
    name: "Weather Today Max Temp"
  today_rain_chance:
    name: "Weather Today Rain Chance"
  today_summary:
    name: "Weather Today Summary"
  today_icon:
    name: "Weather Today Icon"
  today_rain_min:
    name: "Today's Rain Min"
  today_rain_max:
    name: "Today's Rain Max"
  today_sunrise:
    name: "Today's Sunrise"
  today_sunset:
    name: "Today's Sunset"
    
  tomorrow_min:
    name: "Weather Tomorrow Min Temp"
  tomorrow_max:
    name: "Weather Tomorrow Max Temp"
  tomorrow_rain_chance:
    name: "Weather Tomorrow Rain Chance"
  tomorrow_summary:
    name: "Weather Tomorrow Summary"
  tomorrow_icon:
    name: "Weather Tomorrow Icon"
  tomorrow_rain_min:
    name: "Tomorrow Rain Min"
  tomorrow_rain_max:
    name: "Tomorrow Rain Max"
  tomorrow_sunrise:
    name: "Tomorrow Sunrise"
  tomorrow_sunset:
    name: "Tomorrow Sunset"


  warnings_json:
    name: "Weather Warnings (JSON)"
  location_name:
    name: "Weather Location Name"
  out_geohash:
    name: "Weather Resolved Geohash"
  last_update:
    name: "Weather Last Update Time"